# Launch non-login shell
set -g default-command "${SHELL}"

# Modern colors
set -g default-terminal "screen-256color"
set-option -a terminal-overrides ",xterm-256color:RGB"

# Remap prefix from 'C-b' to 'C-a'
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Split panes using "|" and "-" and open in the same directory
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Open new window in the same directory
bind c new-window -c "#{pane_current_path}"

# Mouse friendly
set -g mouse on

# Vim mode
setw -g mode-keys vi

# Fix titlebar
set -g set-titles on
set -g set-titles-string "#T"

# Avoid ESC delay
set -s escape-time 0

# Set scroll history to 100_000 lines
set-option -g history-limit 100000

# Copy to clipboard
set -s copy-command 'pbcopy'
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel

# Clear history with 'C-k'
bind -n C-k clear-history

# Make rename window prompt empty
bind ',' command-prompt "rename-window '%%'"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

set-option -g focus-events on
set-option -g renumber-windows on

# Theme
source-file ~/.config/tmux/themes/catppuccin.tmux